### ISSUE TITLE
TV Al-Hijrah: code 403

### ISSUE THREAD

**Issue by Jerrie-Aries** [MIFNtechnology/siaranMy#50]
App: TiviMate

Saya test link `https://mifntechnology.github.io/siaranMy/mytv.m3u8` menggunakan TiviMate app guna Android mobile. Tak dapat stream channel TV Al Hijrah, `Error: code 403`.

**Comment by ejunds** [comment]
Buat masa ini channel alhijrah memang tak boleh buka.
